[platformio]
src_dir = Arduino
default_envs = prototype_oled

[env]
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@^6.21.5
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer
    adafruit/Adafruit GFX Library@^1.12.6
    adafruit/Adafruit SSD1306@^2.5.17

[env:prototype_oled]
platform = espressif32
board = esp32dev
build_flags =
    -DEPF_HARDWARE_PROFILE=EPF_PROFILE_PROTOTYPE_OLED

[env:prototype_oled_tailscale]
extends = env:prototype_oled
framework = arduino, espidf
board_build.flash_size = 4MB
board_build.partitions = partitions_4mb.csv
build_flags =
    ${env:prototype_oled.build_flags}
    -DEPF_ENABLE_TAILSCALE=1
    -DEPF_ENABLE_SECURE_HTTP=0

[env:ee04_epaper]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino, espidf
board_build.flash_size = 8MB
board_build.partitions = partitions_8mb.csv
build_flags =
    -DEPF_HARDWARE_PROFILE=EPF_PROFILE_EE04_EPAPER
    -DARDUINO_USB_CDC_ON_BOOT=1

[env:ee04_epaper_local]
extends = env:ee04_epaper
build_flags =
    ${env:ee04_epaper.build_flags}
    -DEPF_ENABLE_TAILSCALE=0
