[platformio]
src_dir = Arduino
default_envs = prototype_oled

[env]
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@^6.21.5
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer
    adafruit/Adafruit GFX Library@^1.12.6
    adafruit/Adafruit SSD1306@^2.5.17

[env:prototype_oled]
platform = espressif32
board = esp32dev
build_flags =
    -DEPF_HARDWARE_PROFILE=EPF_PROFILE_PROTOTYPE_OLED

[env:ee04_epaper]
platform = espressif32
board = seeed_xiao_esp32s3
build_flags =
    -DEPF_HARDWARE_PROFILE=EPF_PROFILE_EE04_EPAPER
    -DARDUINO_USB_CDC_ON_BOOT=1
